#!/bin/bash
#
dt=`date --iso=min| sed 's/\+.*//'`

(cd gamma-inaccuracy_src/; R-4.1.3 CMD BATCH --no-save gamma-inaccuracy-4old.R)
R-devel CMD Sweave gamma-inaccuracy.Rnw && pdflatex gamma-inaccuracy

saveD=/tmp/gamma-inacc_${dt}
mkdir -p $saveD
echo -n 'moving *.pdf'" etc to $saveD/ .."
mv gamma-inaccuracy-*.pdf gamma-inaccuracy.{log,tex,pdf} $saveD  ;  echo ' [Ok]'

R-devel-no-ldouble CMD Sweave gamma-inaccuracy.Rnw && pdflatex gamma-inaccuracy
SaveDir=gamma-inaccuracy_no-ldouble
echo -n 'moving *.pdf'" etc to $SaveDir/ .."
mv gamma-inaccuracy-*.pdf gamma-inaccuracy.{log,tex,pdf} $SaveDir ;  echo ' [Ok]'

## get the old ones back:
mv $saveD/* .


