#!/bin/bash
#
dt=`date --iso=min| sed 's/\+.*//'`
R=${R:-R-devel}
# default R-devel (as long as my gamma() improvements are only there)
#
(cd gamma-inaccuracy_src/; R-4.2.1 CMD BATCH --no-save gamma-inaccuracy-4old.R)
fRmd=gamma-inaccuracy.Rmd
bf=`basename $fRmd .Rmd`
logf=${bf}.render_log
$R -e 'rmarkdown::render("'$fRmd'")' 1> $logf 2>&1

saveD=/tmp/gamma-inacc_${dt}
mkdir -p $saveD
echo -n 'moving *.md'" etc to $saveD/ .."
mv ${bf}-*.md ${bf}_files   $saveD  ;  echo ' [Ok]'

logf=${bf}.render_no-ldbl
R-devel-no-ldouble  -e 'rmarkdown::render("'$fRmd'")' 1> $logf 2>&1
SaveDir=${bf}_no-ldouble
echo -n 'moving *.pdf'" etc to $SaveDir/ .."
mv ${bf}-*.md ${bf}_files   $SaveDir ;  echo ' [Ok]'

## get the old ones back:
mv $saveD/* .


